# Generated by Django 5.0.4 on 2024-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.UUIDField(),
        ),
        migrations.AlterUniqueTogether(
            name='refreshtoken',
            unique_together={('user', 'token')},
        ),
    ]
